# Generated by Django 3.1 on 2020-08-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterTB',
            fields=[
                ('regid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('dbstat', models.CharField(default='A', max_length=50)),
            ],
        ),
    ]
