# Generated by Django 3.1 on 2020-11-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prdtb',
            name='title2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prdtb',
            name='title3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
