# Generated by Django 3.1 on 2020-11-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201110_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prdtb',
            name='title2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='prdtb',
            name='title3',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
