# Generated by Django 3.1 on 2020-11-11 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201111_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcommontb',
            name='dbstat',
            field=models.CharField(default='A', max_length=50),
        ),
        migrations.AddField(
            model_name='itemcommontb',
            name='order',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='itemtb',
            name='dbstat',
            field=models.CharField(default='A', max_length=50),
        ),
    ]
