# Generated by Django 3.1 on 2020-11-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201111_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcommontb',
            name='downdata',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itemcommontb',
            name='downdata_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
