# Generated by Django 3.1 on 2020-11-18 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201112_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prdtb',
            name='tag',
        ),
    ]
