# Generated by Django 3.1 on 2020-11-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_prdtb_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtb',
            name='item_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
