# Generated by Django 3.1 on 2020-11-24 01:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_myclasslisttb_item_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSubTB',
            fields=[
                ('ItemSub_idx', models.AutoField(primary_key=True, serialize=False)),
                ('item_code', models.CharField(default='', max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('data', models.CharField(default='', max_length=150)),
                ('order', models.IntegerField(blank=True, default='0', null=True)),
                ('downdata', models.CharField(blank=True, max_length=50, null=True)),
                ('downdata_name', models.CharField(blank=True, max_length=50, null=True)),
                ('dbstat', models.CharField(default='A', max_length=50)),
                ('stime', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('prd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.prdtb')),
            ],
        ),
    ]
