# Generated by Django 3.1 on 2020-12-11 03:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_itemsubtb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInfoTB',
            fields=[
                ('ItemInfo_idx', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('sub_description1', models.CharField(blank=True, default='', max_length=500)),
                ('sub_description2', models.CharField(blank=True, default='', max_length=500)),
                ('dbstat', models.CharField(default='A', max_length=50)),
                ('stime', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='itemcommontb',
            name='iteminfo_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ItemInfoTB_1', to='main.iteminfotb'),
        ),
        migrations.AddField(
            model_name='itemcommontb',
            name='iteminfo_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ItemInfoTB_2', to='main.iteminfotb'),
        ),
        migrations.AddField(
            model_name='itemcommontb',
            name='iteminfo_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ItemInfoTB_3', to='main.iteminfotb'),
        ),
        migrations.AddField(
            model_name='itemcommontb',
            name='iteminfo_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ItemInfoTB_4', to='main.iteminfotb'),
        ),
        migrations.AddField(
            model_name='itemcommontb',
            name='iteminfo_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ItemInfoTB_5', to='main.iteminfotb'),
        ),
    ]
