# Generated by Django 3.1 on 2020-12-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201211_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteminfotb',
            name='description',
        ),
        migrations.RemoveField(
            model_name='iteminfotb',
            name='sub_description1',
        ),
        migrations.RemoveField(
            model_name='iteminfotb',
            name='sub_description2',
        ),
        migrations.AddField(
            model_name='iteminfotb',
            name='downdata',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='iteminfotb',
            name='downdata_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='iteminfotb',
            name='downdata_sub',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
