# Generated by Django 3.1 on 2020-12-23 11:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_iteminfotb_downdata_name_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='codingkit_category_large',
            fields=[
                ('codingkit_category_large_idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('dbstat', models.CharField(default='A', max_length=50)),
                ('stime', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='codingkit_category_small',
            fields=[
                ('codingkit_category_small_idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('dbstat', models.CharField(default='A', max_length=50)),
                ('stime', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('category_large', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.codingkit_category_large')),
            ],
        ),
        migrations.AddField(
            model_name='prdtb',
            name='category_large',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.codingkit_category_large'),
        ),
    ]
