# Generated by Django 3.1 on 2020-12-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20201223_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingkit_category_large',
            name='value',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='codingkit_category_small',
            name='value',
            field=models.CharField(default='', max_length=50),
        ),
    ]
