# Generated by Django 3.1 on 2020-12-23 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20201223_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prdtb',
            old_name='goal',
            new_name='category_small',
        ),
    ]
