# Generated by Django 3.1 on 2020-12-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20201223_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingkit_category_small',
            name='category_large',
        ),
    ]
