# Generated by Django 3.1 on 2020-12-26 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_codingkit_category_small_category_large'),
    ]

    operations = [
        migrations.DeleteModel(
            name='codingkit_category_small',
        ),
    ]
