# Generated by Django 3.1 on 2020-12-26 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_delete_codingkit_category_small'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prdtb',
            old_name='category_small',
            new_name='category_sub',
        ),
    ]
