# Generated by Django 3.1 on 2020-12-26 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20201226_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prdtb',
            old_name='gif',
            new_name='prd_detail_img',
        ),
        migrations.RenameField(
            model_name='prdtb',
            old_name='img',
            new_name='prd_list_img',
        ),
    ]
