# Generated by Django 3.1 on 2020-12-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20201226_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loungelisttb',
            name='description',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
