# Generated by Django 3.1 on 2020-12-26 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20201226_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loungelisttb',
            old_name='description',
            new_name='search_title',
        ),
    ]
