# Generated by Django 3.1 on 2020-12-29 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20201226_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prdtb',
            name='title2',
        ),
        migrations.AddField(
            model_name='loungelisttb',
            name='diagram_img',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='loungelisttb',
            name='down_arduino_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='loungelisttb',
            name='down_mblock_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
