# Generated by Django 3.1 on 2020-12-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20201229_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupontb',
            name='coupon_type',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
