# Generated by Django 3.1 on 2021-01-04 12:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_coupontb_coupon_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='stat_class',
            fields=[
                ('stat_class_idx', models.AutoField(primary_key=True, serialize=False)),
                ('pay_email', models.CharField(blank=True, max_length=50, null=True)),
                ('item_code', models.CharField(default='', max_length=50)),
                ('class_title', models.CharField(default='', max_length=50)),
                ('class_data', models.CharField(default='', max_length=50)),
                ('stime', models.DateTimeField(default=django.utils.timezone.now)),
                ('myclass', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.myclasslisttb')),
                ('pay_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.registertb')),
                ('prd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.prdtb')),
            ],
        ),
    ]
