# Generated by Django 3.1 on 2021-01-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_stat_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat_class',
            name='pay_user',
        ),
        migrations.RemoveField(
            model_name='stat_class',
            name='prd',
        ),
        migrations.AddField(
            model_name='stat_class',
            name='prd_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
