# Generated by Django 3.1 on 2021-01-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20210105_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat_menu',
            name='sub_menu',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
