# Generated by Django 3.1 on 2021-01-05 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20210105_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat_menu',
            old_name='search_title',
            new_name='info_search_etc',
        ),
    ]
